import React from 'react';
import 
{ Typography, 
  // Link,
} from '@mui/material/';
import Grid from '@mui/material/Grid2';
// import Works from '../../works/Works';
// import {
//   AuthorAboutGridFavorites,
//   AuthorAboutFavoritesHeader,
//   AuthorAboutFavoritesGridTitle,
//   AuthorAboutFavoritesTitle,
//   AuthorAboutAuthorsFavoritesResponse,
// } from './AuthorAboutStyles';

const AuthorAbout: React.FC<Props> = ({
  // turnPaddingOn,
  aboutData,
  // bookData,
}) => {
  const questionaireData =  aboutData; // aboutData?.about[0]?.questionaire[0];

  return (
    <>
      <Typography
        color="primary"
      >
        Coming soon...
      </Typography>
      {/* <Grid 
        container
        direction="row"
        justifyContent="flex-start"
        alignItems="center"
      >
        <Works
          authorsPage={true}
          bookData={bookData}
          aboutWorks={true}
          articlePage={true}
        />
      </Grid>
      <Grid 
        container
        direction="row"
        justifyContent="flex-start"
        alignItems="center"
        sx={AuthorAboutGridFavorites(turnPaddingOn)}
      >
        <Grid
          item
          xs={12}
          sm={12}
          md={12}
          lg={12}
          xl={12}
        >
          <Typography
            sx={AuthorAboutFavoritesHeader}
          >
            Favorite
          </Typography>
        </Grid>
        <Grid
          item
          xs={12}
          sm={12}
          md={12}
          lg={12}
          xl={12}
          sx={AuthorAboutFavoritesGridTitle}
        >
          <Typography
            color="#2F4C69"
            sx={AuthorAboutFavoritesTitle}
          >
            Video Game Console:
          </Typography>
          <Link 
            href={questionaireData?.FavoriteVideoGameConsole?.link}
            underline="none"
            target="_blank"
            rel="noopener"
            sx={AuthorAboutAuthorsFavoritesResponse}
          >
            {questionaireData?.FavoriteVideoGameConsole?.name}
          </Link>
        </Grid>
        <Grid
          item
          xs={12}
          sm={12}
          md={12}
          lg={12}
          xl={12}
          sx={AuthorAboutFavoritesGridTitle}
        >
          <Typography
            color="#2F4C69"
            sx={AuthorAboutFavoritesTitle}
          >
            Video Game:
          </Typography>
          <Link 
            href={questionaireData?.FavoriteVideoGame?.link}
            underline="none"
            target="_blank"
            rel="noopener"
            sx={AuthorAboutAuthorsFavoritesResponse}
          >
            {questionaireData?.FavoriteVideoGame?.name}
          </Link>     
        </Grid>
        <Grid
          item
          xs={12}
          sm={12}
          md={12}
          lg={12}
          xl={12}
          sx={AuthorAboutFavoritesGridTitle}
        >
          <Typography
            color="#2F4C69"
            sx={AuthorAboutFavoritesTitle}
          >
            Video Game Series:
          </Typography>
          <Link 
            href={questionaireData?.FavoriteVideoGameSeries?.link}
            underline="none"
            target="_blank"
            rel="noopener"
            sx={AuthorAboutAuthorsFavoritesResponse}
          >
            {questionaireData?.FavoriteVideoGameSeries?.name}
          </Link>
        </Grid>
        <Grid
          item
          xs={12}
          sm={12}
          md={12}
          lg={12}
          xl={12}
          sx={AuthorAboutFavoritesGridTitle}
        >
          <Typography
            color="#2F4C69"
            sx={AuthorAboutFavoritesTitle}
          >
            Video Game Genere:
          </Typography>
          <Link 
            href={questionaireData?.FavoriteVideoGameGenere?.link}
            underline="none"
            target="_blank"
            rel="noopener"
            sx={AuthorAboutAuthorsFavoritesResponse}
          >
            {questionaireData?.FavoriteVideoGameGenere?.name}
          </Link>
        </Grid>
        <Grid
          item
          xs={12}
          sm={12}
          md={12}
          lg={12}
          xl={12}
          sx={AuthorAboutFavoritesGridTitle}
        >
          <Typography
            color="#2F4C69"
            sx={AuthorAboutFavoritesTitle}
          >
            JRPG:
          </Typography>
          <Link 
            href={questionaireData?.FavoriteJRPG?.link}
            underline="none"
            target="_blank"
            rel="noopener"
            sx={AuthorAboutAuthorsFavoritesResponse}
          >
            {questionaireData?.FavoriteJRPG?.name} 
          </Link>
        </Grid>
        <Grid
          item
          xs={12}
          sm={12}
          md={12}
          lg={12}
          xl={12}
          sx={AuthorAboutFavoritesGridTitle}
        >
          <Typography
            color="#2F4C69"
            sx={AuthorAboutFavoritesTitle}
          >
            RPG:
          </Typography>
          <Link 
            href={questionaireData?.FavoriteRPG?.link}
            underline="none"
            target="_blank"
            rel="noopener"
            sx={AuthorAboutAuthorsFavoritesResponse}
          >
            {questionaireData?.FavoriteRPG?.name}
          </Link>
        </Grid>
        <Grid
          item
          sx={AuthorAboutFavoritesGridTitle}
        >
          <Typography
            color="#2F4C69"
            sx={AuthorAboutFavoritesTitle}
          >
            Action Game:
          </Typography>
          <Link 
            href={questionaireData?.FavoriteActionGame?.link}
            underline="none"
            target="_blank"
            rel="noopener"
            sx={AuthorAboutAuthorsFavoritesResponse}
          >
            {questionaireData?.FavoriteActionGame?.name}
          </Link>
        </Grid>
        <Grid
          item
          xs={12}
          sm={12}
          md={12}
          lg={12}
          xl={12}
          sx={AuthorAboutFavoritesGridTitle}
        >
          <Typography
            color="#2F4C69"
            sx={AuthorAboutFavoritesTitle}
          >
            Platformer:
          </Typography>
          <Link 
            href={questionaireData?.FavoritePlatformer?.link}
            underline="none"
            target="_blank"
            rel="noopener"
            sx={AuthorAboutAuthorsFavoritesResponse}
          >
            {questionaireData?.FavoritePlatformer?.name}
          </Link>
        </Grid>
        <Grid
          item
          xs={12}
          sm={12}
          md={12}
          lg={12}
          xl={12}
          sx={AuthorAboutFavoritesGridTitle}
        >
          <Typography
            color="#2F4C69"
            sx={AuthorAboutFavoritesTitle}
          >
            Horror:
          </Typography>
          <Link 
            href={questionaireData?.FavoriteHorror?.link}
            underline="none"
            target="_blank"
            rel="noopener"
            sx={AuthorAboutAuthorsFavoritesResponse}
          >
            {questionaireData?.FavoriteHorror?.name}
          </Link>
        </Grid>
        <Grid
          item
          xs={12}
          sm={12}
          md={12}
          lg={12}
          xl={12}
          sx={AuthorAboutFavoritesGridTitle}
        >
          <Typography
            color="#2F4C69"
            sx={AuthorAboutFavoritesTitle}
          >
            {'Beat \'em up:'}
          </Typography>
          <Link 
            href={questionaireData?.FavoriteBeatEmUp?.link}
            underline="none"
            target="_blank"
            rel="noopener"
            sx={AuthorAboutAuthorsFavoritesResponse}
          >
            {questionaireData?.FavoriteBeatEmUp?.name}
          </Link>
        </Grid>
        <Grid
          item
          xs={12}
          sm={12}
          md={12}
          lg={12}
          xl={12}
          sx={AuthorAboutFavoritesGridTitle}
        >
          <Typography
            color="#2F4C69"
            sx={AuthorAboutFavoritesTitle}
          >
            Stealth Game:
          </Typography>
          <Link 
            href={questionaireData?.FavoriteStealthGame?.link}
            underline="none"
            target="_blank"
            rel="noopener"
            sx={AuthorAboutAuthorsFavoritesResponse}
          >
            {questionaireData?.FavoriteStealthGame?.name}
          </Link>
        </Grid>
        <Grid
          item
          xs={12}
          sm={12}
          md={12}
          lg={12}
          xl={12}
          sx={AuthorAboutFavoritesGridTitle}
        >
          <Typography
            color="#2F4C69"
            sx={AuthorAboutFavoritesTitle}
          >
            Life Simulation Game:
          </Typography>
          <Link 
            href={questionaireData?.FavoriteLifeSimulationGame?.link}
            underline="none"
            target="_blank"
            rel="noopener"
            sx={AuthorAboutAuthorsFavoritesResponse}
          >
            {questionaireData?.FavoriteLifeSimulationGame?.name}
          </Link>
        </Grid>
        <Grid
          item
          xs={12}
          sm={12}
          md={12}
          lg={12}
          xl={12}
          sx={AuthorAboutFavoritesGridTitle}
        >
          <Typography
            color="#2F4C69"
            sx={AuthorAboutFavoritesTitle}
          >
            Visual Novel:
          </Typography>
          <Link 
            href={questionaireData?.FavoriteVisualNovel?.link}
            underline="none"
            target="_blank"
            rel="noopener"
            sx={AuthorAboutAuthorsFavoritesResponse}
          >
            {questionaireData?.FavoriteVisualNovel?.name}
          </Link>
        </Grid>
        <Grid
          item
          xs={12}
          sm={12}
          md={12}
          lg={12}
          xl={12}
          sx={AuthorAboutFavoritesGridTitle}
        >
          <Typography
            color="#2F4C69"
            sx={AuthorAboutFavoritesTitle}
          >
            RTS:
          </Typography>
          <Link 
            href={questionaireData?.FavoriteRTS?.link}
            underline="none"
            target="_blank"
            rel="noopener"
            sx={AuthorAboutAuthorsFavoritesResponse}
          >
            {questionaireData?.FavoriteRTS?.name}
          </Link>
        </Grid>
        <Grid
          item
          xs={12}
          sm={12}
          md={12}
          lg={12}
          xl={12}
          sx={AuthorAboutFavoritesGridTitle}
        >
          <Typography
            color="#2F4C69"
            sx={AuthorAboutFavoritesTitle}
          >
            MMO:
          </Typography>
          <Link 
            href={questionaireData?.FavoriteMMO?.link}
            underline="none"
            target="_blank"
            rel="noopener"
            sx={AuthorAboutAuthorsFavoritesResponse}
          >
            {questionaireData?.FavoriteMMO?.name}
          </Link>
        </Grid>
        <Grid
          item
          xs={12}
          sm={12}
          md={12}
          lg={12}
          xl={12}
          sx={AuthorAboutFavoritesGridTitle}
        >
          <Typography
            color="#2F4C69"
            sx={AuthorAboutFavoritesTitle}
          >
            Shooter:
          </Typography>
          <Link 
            href={questionaireData?.FavoriteShooter?.link}
            underline="none"
            target="_blank"
            rel="noopener"
            sx={AuthorAboutAuthorsFavoritesResponse}
          >
            {questionaireData?.FavoriteShooter?.name}
          </Link>
        </Grid>
        <Grid
          item
          xs={12}
          sm={12}
          md={12}
          lg={12}
          xl={12}
          sx={AuthorAboutFavoritesGridTitle}
        >
          <Typography
            color="#2F4C69"
            sx={AuthorAboutFavoritesTitle}
          >
            Fighting Game:
          </Typography>
          <Link 
            href={questionaireData?.FavoriteFightingGame?.link}
            underline="none"
            target="_blank"
            rel="noopener"
            sx={AuthorAboutAuthorsFavoritesResponse}
          >
            {questionaireData?.FavoriteFightingGame?.name}
          </Link>
        </Grid>
        <Grid
          item
          xs={12}
          sm={12}
          md={12}
          lg={12}
          xl={12}
          sx={AuthorAboutFavoritesGridTitle}
        >
          <Typography
            color="#2F4C69"
            sx={AuthorAboutFavoritesTitle}
          >
            Racing Game:
          </Typography>
          <Link 
            href={questionaireData?.FavoriteRacingGame?.link}
            underline="none"
            target="_blank"
            rel="noopener"
            sx={AuthorAboutAuthorsFavoritesResponse}
          >
            {questionaireData?.FavoriteRacingGame?.name}
          </Link>
        </Grid>
        <Grid
          item
          xs={12}
          sm={12}
          md={12}
          lg={12}
          xl={12}
          sx={AuthorAboutFavoritesGridTitle}
        >
          <Typography
            color="#2F4C69"
            sx={AuthorAboutFavoritesTitle}
          >
            Sports Game:
          </Typography>
          <Link 
            href={questionaireData?.FavoriteSportsGame?.link}
            underline="none"
            target="_blank"
            rel="noopener"
            sx={AuthorAboutAuthorsFavoritesResponse}
          >
            {questionaireData?.FavoriteSportsGame?.name}
          </Link>
        </Grid>
        <Grid
          item
          xs={12}
          sm={12}
          md={12}
          lg={12}
          xl={12}
          sx={AuthorAboutFavoritesGridTitle}
        >
          <Typography
            color="#2F4C69"
            sx={AuthorAboutFavoritesTitle}
          >
            Waifu:
          </Typography>
          <Link 
            href={questionaireData?.FavoriteWaifu?.link}
            underline="none"
            target="_blank"
            rel="noopener"
            sx={AuthorAboutAuthorsFavoritesResponse}
          >
            {questionaireData?.FavoriteWaifu?.name}
          </Link>
        </Grid>
        <Grid
          item
          xs={12}
          sm={12}
          md={12}
          lg={12}
          xl={12}
          sx={AuthorAboutFavoritesGridTitle}
        >
          <Typography
            color="#2F4C69"
            sx={AuthorAboutFavoritesTitle}
          >
            Anime:
          </Typography>
          <Link 
            href={questionaireData?.FavoriteAnime?.link}
            underline="none"
            target="_blank"
            rel="noopener"
            sx={AuthorAboutAuthorsFavoritesResponse}
          >
            {questionaireData?.FavoriteAnime?.name}
          </Link>
        </Grid>
        <Grid
          item
          xs={12}
          sm={12}
          md={12}
          lg={12}
          xl={12}
          sx={AuthorAboutFavoritesGridTitle}
        >
          <Typography
            color="#2F4C69"
            sx={AuthorAboutFavoritesTitle}
          >
            Movie:
          </Typography>
          <Link 
            href={questionaireData?.FavoriteMovie?.link}
            underline="none"
            target="_blank"
            rel="noopener"
            sx={AuthorAboutAuthorsFavoritesResponse}
          >
            {questionaireData?.FavoriteMovie?.name}
          </Link>
        </Grid>
        <Grid
          item
          xs={12}
          sm={12}
          md={12}
          lg={12}
          xl={12}
          sx={AuthorAboutFavoritesGridTitle}
        >
          <Typography
            color="#2F4C69"
            sx={AuthorAboutFavoritesTitle}
          >
            Food:
          </Typography>
          <Link 
            href={questionaireData?.FavoriteFood?.link}
            underline="none"
            target="_blank"
            rel="noopener"
            sx={AuthorAboutAuthorsFavoritesResponse}
          >
            {questionaireData?.FavoriteFood?.name}
          </Link>
        </Grid>
        <Grid
          item
          xs={12}
          sm={12}
          md={12}
          lg={12}
          xl={12}
          sx={AuthorAboutFavoritesGridTitle}
        >
          <Typography
            color="#2F4C69"
            sx={AuthorAboutFavoritesTitle}
          >
            Card Game:
          </Typography>
          <Link 
            href={questionaireData?.FavoriteCardGame?.link}
            underline="none"
            target="_blank"
            rel="noopener"
            sx={AuthorAboutAuthorsFavoritesResponse}
          >
            {questionaireData?.FavoriteCardGame?.name}
          </Link>  
        </Grid>
        <Grid
          item
          xs={12}
          sm={12}
          md={12}
          lg={12}
          xl={12}
          sx={AuthorAboutFavoritesGridTitle}
        >
          <Typography
            color="#2F4C69"
            sx={AuthorAboutFavoritesTitle}
          >
            Board Game:
          </Typography>
          <Link 
            href={questionaireData?.FavoriteBoardGame?.link}
            underline="none"
            target="_blank"
            rel="noopener"
            sx={AuthorAboutAuthorsFavoritesResponse}
          >
            {questionaireData?.FavoriteBoardGame?.name}
          </Link>
        </Grid>
      </Grid> */}
    </>
  );
};

export type Props = {
  turnPaddingOn: boolean,
  aboutData: any;
  bookData: any;
};

export default AuthorAbout;
